In [43]:
import pandas as pd
from IPython.display import display

#Load dataset
df = pd.read_csv("student_performance.csv")

# Display first 5 rows
display(df.head())

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness
0,S0001,24,Female,75.95,2,7.94,52.36,33.88,9,1,4.02,2.99,1.65,Good,High
1,S0002,21,Female,73.96,3,8.84,28.23,40.51,2,5,3.56,2.22,2.67,Average,Moderate
2,S0003,22,Male,51.28,6,3.45,29.81,23.90,19,3,1.48,4.71,4.33,Good,Moderate
3,S0004,24,Female,67.06,2,4.62,27.78,62.89,9,0,2.93,3.35,4.95,Good,Moderate
4,S0005,20,Female,69.01,8,4.15,77.15,64.04,17,0,3.74,2.63,2.27,Poor,High

In [44]:
# Display last 5 rows
display(df.tail())

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness
995,S0996,22,Female,74.62,2,4.92,24.23,95.51,13,4,2.43,4.17,1.67,Excellent,Moderate
996,S0997,18,Female,78.86,6,7.97,20.35,61.09,11,0,2.51,1.77,2.68,Average,Low
997,S0998,21,Female,93.28,5,2.33,95.46,0.13,10,1,2.67,3.67,2.94,Good,High
998,S0999,25,Male,99.04,8,2.26,91.85,89.40,19,4,3.19,1.37,2.03,Average,High
999,S1000,20,Female,70.38,5,5.51,4.70,52.17,18,4,3.21,3.03,3.11,Average,High

In [45]:
# Display number of rows and columns
print(df.shape)

(1000, 15)

In [47]:
# Display the column names
print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Attendance_Percentage',
       'Assignments_Completed', 'Class_Participation', 'Midterm_Grade',
       'Final_Grade', 'Study_Hours_per_Week', 'Projects_Submitted',
       'Teaching_Clarity', 'Teaching_Helpfulness', 'Feedback_Timeliness',
       'Student_Performance', 'Teaching_Effectiveness'],
      dtype='object')

In [49]:
# Print datatypes
print(df.dtypes)

Student_ID                 object
Age                         int64
Gender                     object
Attendance_Percentage     float64
Assignments_Completed       int64
Class_Participation       float64
Midterm_Grade             float64
Final_Grade               float64
Study_Hours_per_Week        int64
Projects_Submitted          int64
Teaching_Clarity          float64
Teaching_Helpfulness      float64
Feedback_Timeliness       float64
Student_Performance        object
Teaching_Effectiveness     object
dtype: object

In [51]:
# Display information about the DataFrame
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student_ID              1000 non-null   object
 1   Age                     1000 non-null   int64
 2   Gender                  1000 non-null   object
 3   Attendance_Percentage   1000 non-null   float64
 4   Assignments_Completed   1000 non-null   int64
 5   Class_Participation     1000 non-null   float64
 6   Midterm_Grade           1000 non-null   float64
 7   Final_Grade             1000 non-null   float64
 8   Study_Hours_per_Week    1000 non-null   int64
 9   Projects_Submitted      1000 non-null   int64
 10  Teaching_Clarity        1000 non-null   float64
 11  Teaching_Helpfulness    1000 non-null   float64
 12  Feedback_Timeliness     1000 non-null   float64
 13  Student_Performance     1000 non-null   object
 14  Teaching_Effectiveness  1000 non-null   object
dtypes: float64(7), int64(4), object(4)
memory usage: 117.3+ KB
None

In [52]:
# Display summary statistics of numerical columns
display(df.describe())

,Age,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness
count,1000.0000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,21.4980,74.907990,4.996000,5.025990,49.00406,48.520150,9.531000,2.338000,3.024860,2.969660,3.020800
std,2.3081,14.313514,3.189068,2.858739,28.66500,29.521588,5.670555,1.744936,1.169256,1.142438,1.138803
min,18.0000,50.080000,0.000000,0.010000,0.02000,0.060000,0.000000,0.000000,1.010000,1.010000,1.000000
25%,19.7500,62.837500,2.000000,2.562500,24.41000,22.282500,5.000000,1.000000,2.050000,1.997500,2.100000
50%,21.0000,75.280000,5.000000,5.105000,48.13000,48.710000,9.000000,2.000000,3.010000,3.000000,3.010000
75%,24.0000,86.910000,8.000000,7.532500,73.79750,73.450000,14.000000,4.000000,4.050000,3.940000,3.970000
max,25.0000,99.920000,10.000000,9.980000,99.75000,99.980000,19.000000,5.000000,5.000000,5.000000,5.000000

In [14]:
# Check the number of missing values in each column
df.isnull().sum()

Student_ID                0
Age                       0
Gender                    0
Attendance_Percentage     0
Assignments_Completed     0
Class_Participation       0
Midterm_Grade             0
Final_Grade               0
Study_Hours_per_Week      0
Projects_Submitted        0
Teaching_Clarity          0
Teaching_Helpfulness      0
Feedback_Timeliness       0
Student_Performance       0
Teaching_Effectiveness    0
dtype: int64

In [15]:
# Check whether any missing value exists in each column
df.isnull().any()

Student_ID                False
Age                       False
Gender                    False
Attendance_Percentage     False
Assignments_Completed     False
Class_Participation       False
Midterm_Grade             False
Final_Grade               False
Study_Hours_per_Week      False
Projects_Submitted        False
Teaching_Clarity          False
Teaching_Helpfulness      False
Feedback_Timeliness       False
Student_Performance       False
Teaching_Effectiveness    False
dtype: bool

In [18]:
# Find columns containing missing values
null_columns = df.columns[df.isnull().any()]
null_columns

Index([], dtype='object')

In [23]:
# Handle Missing Values

# Fill missing values in a numerical column with the mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill missing values in a numerical column with the median
df['Final_GRade'] = df['Final_Grade'].fillna(df['Final_Grade'].median())

# Fill missing values in a categorical column with the mode
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [27]:
# Check duplicate rows
print(df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

print(df.duplicated().sum())

0
0

In [54]:
# Select a single column
df['Age']

0      24
1      21
2      22
3      24
4      20
       ..
995    22
996    18
997    21
998    25
999    20
Name: Age, Length: 1000, dtype: int64

In [31]:
# Select multiple columns
df[['Age', 'Gender', 'Final_Grade']]

     Age  Gender  Final_Grade
0     24  Female        33.88
1     21  Female        40.51
2     22    Male        23.90
3     24  Female        62.89
4     20  Female        64.04
..   ...     ...          ...
995   22  Female        95.51
996   18  Female        61.09
997   21  Female         0.13
998   25    Male        89.40
999   20  Female        52.17

[1000 rows x 3 columns]

In [34]:
# Select the first row using its label
df.loc[0]

Student_ID                 S0001
Age                           24
Gender                    Female
Attendance_Percentage      75.95
Assignments_Completed          2
Class_Participation         7.94
Midterm_Grade              52.36
Final_Grade                33.88
Study_Hours_per_Week           9
Projects_Submitted             1
Teaching_Clarity            4.02
Teaching_Helpfulness        2.99
Feedback_Timeliness         1.65
Student_Performance         Good
Teaching_Effectiveness      High
Final_GRade                33.88
Name: 0, dtype: object

In [35]:
# Select the first five rows using their labels
df.loc[0:4]

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness,Final_GRade
0,S0001,24,Female,75.95,2,7.94,52.36,33.88,9,1,4.02,2.99,1.65,Good,High,33.88
1,S0002,21,Female,73.96,3,8.84,28.23,40.51,2,5,3.56,2.22,2.67,Average,Moderate,40.51
2,S0003,22,Male,51.28,6,3.45,29.81,23.90,19,3,1.48,4.71,4.33,Good,Moderate,23.90
3,S0004,24,Female,67.06,2,4.62,27.78,62.89,9,0,2.93,3.35,4.95,Good,Moderate,62.89
4,S0005,20,Female,69.01,8,4.15,77.15,64.04,17,0,3.74,2.63,2.27,Poor,High,64.04

In [36]:
# Select the first five rows using their integer positions
df.iloc[0:5]

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness,Final_GRade
0,S0001,24,Female,75.95,2,7.94,52.36,33.88,9,1,4.02,2.99,1.65,Good,High,33.88
1,S0002,21,Female,73.96,3,8.84,28.23,40.51,2,5,3.56,2.22,2.67,Average,Moderate,40.51
2,S0003,22,Male,51.28,6,3.45,29.81,23.90,19,3,1.48,4.71,4.33,Good,Moderate,23.90
3,S0004,24,Female,67.06,2,4.62,27.78,62.89,9,0,2.93,3.35,4.95,Good,Moderate,62.89
4,S0005,20,Female,69.01,8,4.15,77.15,64.04,17,0,3.74,2.63,2.27,Poor,High,64.04

In [38]:
# Select the Name column for the first five rows
df.loc[0:4, 'Student_ID']

0    S0001
1    S0002
2    S0003
3    S0004
4    S0005
Name: Student_ID, dtype: object

In [62]:
# Filtering data

high_score = df[df['Final_Grade'] > 80]
display(high_score)

display(df[(df['Attendance_Percentage'] > 95) & (df['Study_Hours_per_Week'] > 15)])

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness
5,S0006,25,Male,69.94,7,0.13,65.19,85.05,13,5,4.12,3.60,3.13,Good,High
15,S0016,22,Male,50.38,10,5.32,39.92,92.43,16,4,4.40,2.94,2.08,Average,Moderate
21,S0022,22,Male,96.72,10,7.32,13.57,95.39,1,5,1.13,1.05,1.23,Average,Moderate
22,S0023,19,Other,67.58,2,8.82,89.36,86.56,6,3,3.91,1.69,2.65,Good,Moderate
32,S0033,21,Other,85.81,8,3.36,92.41,93.40,11,2,3.09,3.38,3.05,Average,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,S0974,20,Male,86.11,6,4.64,3.74,88.24,19,0,3.05,1.66,4.64,Good,Moderate
989,S0990,25,Male,68.77,0,9.95,92.37,99.98,6,4,4.91,4.65,3.73,Average,High
993,S0994,21,Male,69.33,5,7.67,31.03,92.06,13,1,3.02,3.41,3.87,Average,High
995,S0996,22,Female,74.62,2,4.92,24.23,95.51,13,4,2.43,4.17,1.67,Excellent,Moderate
998,S0999,25,Male,99.04,8,2.26,91.85,89.40,19,4,3.19,1.37,2.03,Average,High

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness
123,S0124,24,Female,97.88,6,6.77,34.18,44.76,19,1,4.36,2.04,4.02,Poor,Low
256,S0257,24,Female,97.98,8,0.70,67.58,41.83,16,5,2.30,1.63,2.66,Average,Moderate
330,S0331,18,Male,99.00,10,2.20,43.60,22.03,17,5,4.66,1.67,4.37,Excellent,Moderate
344,S0345,20,Male,97.15,3,8.29,86.35,21.99,16,5,3.64,3.05,2.29,Good,High
364,S0365,24,Male,99.23,7,9.92,90.32,22.30,16,0,3.70,1.47,1.22,Poor,Moderate
365,S0366,24,Female,96.87,5,6.64,2.46,40.79,16,1,1.23,4.04,4.05,Excellent,High
389,S0390,18,Male,99.59,8,7.36,36.70,33.82,18,2,4.50,1.09,4.74,Excellent,High
455,S0456,20,Male,96.66,8,6.70,40.18,7.74,17,0,1.99,4.09,3.13,Poor,Moderate
591,S0592,25,Female,98.22,10,6.17,31.46,77.00,18,1,2.01,1.62,1.34,Good,Moderate
691,S0692,23,Female,95.36,9,4.44,20.21,21.77,18,0,2.14,3.89,4.67,Good,Low
713,S0714,21,Female,98.14,7,2.11,20.13,85.52,18,0,2.88,1.72,4.08,Poor,Moderate
825,S0826,21,Male,97.75,7,5.35,10.14,1.59,17,2,1.38,2.27,2.74,Good,Moderate
932,S0933,18,Female,99.20,4,0.42,86.07,63.84,19,2,2.32,1.63,3.61,Poor,High
998,S0999,25,Male,99.04,8,2.26,91.85,89.40,19,4,3.19,1.37,2.03,Average,High

In [64]:
# Sort the data

# Ascending order
display(df.sort_values('Age'))

# Descending order
df.sort_values('Projects_Submitted', ascending=False)

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness
996,S0997,18,Female,78.86,6,7.97,20.35,61.09,11,0,2.51,1.77,2.68,Average,Low
31,S0032,18,Other,80.52,7,2.68,73.24,25.64,17,0,4.74,3.00,1.56,Good,High
965,S0966,18,Male,60.07,2,1.38,34.19,64.95,15,2,2.48,4.44,3.66,Average,High
961,S0962,18,Female,94.02,6,9.89,44.28,6.17,16,4,3.52,4.31,2.67,Average,Moderate
972,S0973,18,Female,95.47,9,8.91,30.18,1.00,11,0,4.04,2.16,1.85,Good,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,S0999,25,Male,99.04,8,2.26,91.85,89.40,19,4,3.19,1.37,2.03,Average,High
984,S0985,25,Male,73.13,9,1.20,9.92,8.98,17,4,2.72,4.98,2.95,Good,High
18,S0019,25,Other,62.17,1,5.41,15.39,36.94,6,2,2.20,4.60,2.44,Good,Low
989,S0990,25,Male,68.77,0,9.95,92.37,99.98,6,4,4.91,4.65,3.73,Average,High
17,S0018,25,Female,94.90,6,2.97,65.29,28.92,7,5,4.37,1.03,4.48,Average,Low

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness
12,S0013,20,Other,97.78,2,4.30,93.25,13.33,3,5,1.44,4.59,4.61,Good,High
992,S0993,19,Male,88.09,8,6.74,23.56,14.12,9,5,4.79,4.67,4.73,Average,Low
5,S0006,25,Male,69.94,7,0.13,65.19,85.05,13,5,4.12,3.60,3.13,Good,High
742,S0743,19,Female,79.14,6,0.52,60.14,29.95,14,5,3.81,4.25,1.57,Good,Low
747,S0748,24,Male,91.57,7,8.30,44.60,98.03,1,5,4.88,3.88,4.24,Good,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,S0973,18,Female,95.47,9,8.91,30.18,1.00,11,0,4.04,2.16,1.85,Good,Low
973,S0974,20,Male,86.11,6,4.64,3.74,88.24,19,0,3.05,1.66,4.64,Good,Moderate
980,S0981,21,Female,63.79,6,6.95,18.69,38.95,18,0,4.34,3.25,2.59,Good,High
4,S0005,20,Female,69.01,8,4.15,77.15,64.04,17,0,3.74,2.63,2.27,Poor,High
3,S0004,24,Female,67.06,2,4.62,27.78,62.89,9,0,2.93,3.35,4.95,Good,Moderate

In [66]:
#Find unique values in Teaching_Effectiveness column
display(df['Teaching_Effectiveness'].unique())

# Count the number of unique values in Gender column
display(df['Gender'].nunique())

# Count the frequency of each value in the Student_Performance column
display(df['Student_Performance'].value_counts())

array(['High', 'Moderate', 'Low'], dtype=object)

3

Student_Performance
Good         413
Average      291
Excellent    203
Poor          93
Name: count, dtype: int64

In [77]:
# Basic mathematical operations

print("Mean:",df['Midterm_Grade'].mean())
print("Median:",df['Midterm_Grade'].median())

# Mode for numerical data
print("Mode:",df['Midterm_Grade'].mode()[0])

# Mode for categorical data
print("Mode:",df['Gender'].mode()[0])

print("Max:",df['Midterm_Grade'].max())
print("Min:",df['Midterm_Grade'].min())
print("Sum:",df['Midterm_Grade'].sum())
print("Standard Deviation:",df['Midterm_Grade'].std())
print("Variance:", df['Midterm_Grade'].var())
print("Range:", df['Midterm_Grade'].max() - df['Midterm_Grade'].min())
print("Count:", df['Midterm_Grade'].count())

Mean: 49.004059999999996
Median: 48.129999999999995
Mode: 16.46
Mode: Female
Max: 99.75
Min: 0.02
Sum: 49004.06
Standard Deviation: 28.664999950087886
Variance: 821.6822221385386
Range: 99.73
Count: 1000

In [79]:
# Calculate the mean, minimum, and maximum midterm grade for each teaching effectiveness level
df.groupby('Teaching_Effectiveness')['Midterm_Grade'].agg(['mean', 'min', 'max'])

                             mean   min    max
Teaching_Effectiveness
High                    50.997543  0.68  99.75
Low                     48.669268  0.51  99.56
Moderate                48.001126  0.02  99.55

In [81]:
# Create a new column
df['Total_Grade'] = df['Midterm_Grade'] + df['Final_Grade']
df.head()

,Student_ID,Age,Gender,Attendance_Percentage,Assignments_Completed,Class_Participation,Midterm_Grade,Final_Grade,Study_Hours_per_Week,Projects_Submitted,Teaching_Clarity,Teaching_Helpfulness,Feedback_Timeliness,Student_Performance,Teaching_Effectiveness,Total_Grade
0,S0001,24,Female,75.95,2,7.94,52.36,33.88,9,1,4.02,2.99,1.65,Good,High,86.24
1,S0002,21,Female,73.96,3,8.84,28.23,40.51,2,5,3.56,2.22,2.67,Average,Moderate,68.74
2,S0003,22,Male,51.28,6,3.45,29.81,23.90,19,3,1.48,4.71,4.33,Good,Moderate,53.71
3,S0004,24,Female,67.06,2,4.62,27.78,62.89,9,0,2.93,3.35,4.95,Good,Moderate,90.67
4,S0005,20,Female,69.01,8,4.15,77.15,64.04,17,0,3.74,2.63,2.27,Poor,High,141.19

In [86]:
# Rename column
df.rename(columns={'Attendance_Percentage': 'Attendance'}, inplace=True)
df.columns.tolist()

['Student_ID',
 'Age',
 'Gender',
 'Attendance',
 'Assignments_Completed',
 'Class_Participation',
 'Midterm_Grade',
 'Final_Grade',
 'Study_Hours_per_Week',
 'Projects_Submitted',
 'Teaching_Clarity',
 'Teaching_Helpfulness',
 'Feedback_Timeliness',
 'Student_Performance',
 'Teaching_Effectiveness',
 'Total_Grade']

In [90]:
# Delete column
# df.drop('Total_Grade', axis=1, inplace=True)
df.columns.tolist()

['Student_ID',
 'Age',
 'Gender',
 'Attendance',
 'Assignments_Completed',
 'Class_Participation',
 'Midterm_Grade',
 'Final_Grade',
 'Study_Hours_per_Week',
 'Projects_Submitted',
 'Teaching_Clarity',
 'Teaching_Helpfulness',
 'Feedback_Timeliness',
 'Student_Performance',
 'Teaching_Effectiveness']